### ISSUE TITLE
[macOs] Unhandled Exception: FileSystemException: Cannot open file, path = '/Users/username/Library/Containers/com.example.packagename/Data/Library/LaunchAgents/AppName.plist' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by newnishad** [leanflutter/launch_at_startup#18]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot open file, path = '/Users/username/Library/Containers/com.example.packagename/Data/Library/LaunchAgents/AppName.plist' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      AppAutoLauncherImplMacOS.enable
package:launch_at_startup/src/app_auto_launcher_impl_macos.dart:37
#5      LaunchAtStartup.enable
package:launch_at_startup/src/launch_at_startup.dart:34
#6      main
package:home_services/main.dart:49
<asynchronous suspension>

**Comment by lijy91** [comment]
Please switch to non-sandbox mode, macOS only supports non-sandbox mode now.
