### ISSUE TITLE
Error 0x80070005: 拒绝访问。

### ISSUE THREAD

**Issue by dearjasonding** [leanflutter/launch_at_startup#21]
------- STACK TRACE -------
#0      RegistryKey.createValue (package:win32_registry/src/registry_key.dart:73)
#1      AppAutoLauncherImplWindows.enable (package:launch_at_startup/src/app_auto_launcher_impl_windows.dart:31)
#2      LaunchAtStartup.enable (package:launch_at_startup/src/launch_at_startup.dart:47)

**Comment by lijy91** [comment]
请更新到 0.3.0
