### ISSUE TITLE
[MacOS]: Icon for Allow in Background

### ISSUE THREAD

**Issue by YosaRama** [leanflutter/launch_at_startup#23]
I would to change icon for "Allow in Background" on MacOS. currently my application already can "Allow in Background" working on Windows and also on MacOS. but I've problem with the icon. 

In Windows that's look fine, but on MacOS it will look like this:
<img width="465" alt="Screenshot 2023-08-31 at 21 22 12" src="https://github.com/leanflutter/launch_at_startup/assets/67961793/426e0d24-1df8-44d7-bfb8-82a94db8f1f8">

I hope there are something I can do for change this one.

Thanks!

**Comment by lijy91** [comment]
Fixed on this pr https://github.com/leanflutter/launch_at_startup/pull/27
