### ISSUE TITLE
OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by chentianxin** [leanflutter/launch_at_startup#3]
run example error
It is recommended to check whether there is a corresponding file before operating the file

![87BAE8FCFCCA6A358C881162D53640A8](https://user-images.githubusercontent.com/49486355/151650012-e9a85217-5f81-4c50-b6eb-fbe6189bff22.png)

**Comment by lijy91** [comment]
Fixed, please upgrade to `v0.1.3`
