### ISSUE TITLE
[windows] isEnabled is not working when args are passed

### ISSUE THREAD

**Issue by anurag-MANIT** [leanflutter/launch_at_startup#9]
https://github.com/leanflutter/launch_at_startup/blob/main/lib/src/app_auto_launcher_impl_windows.dart#:~:text=String%3F%20value,value%20%3D%3D%20appPath%3B

The path returned by reg. will contain the concatenated args and comparing it with app path will never gives true

Also there should be check that if no args is passed then path should not be joined with args, this is adding an extra space to the path string. Due to this disabling of auto launch is failing

**Comment by lijy91** [comment]
fixed in pr https://github.com/leanflutter/launch_at_startup/pull/10 , Please update to 0.1.8
